name: Contirbutor requests review demo

on:
  pull_request_target:
    types: [review_requested, review_request_removed]

jobs:
  make_request:
    runs-on: ubuntu-latest
    steps:
  
      - name: Hello World Step
        run: echo "review requested or review removed"

